pipeline {
    agent any

    environment {
        NODE_VERSION = '20'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-token',
                    url: 'https://github.com/alexiosgrig/ci-cd-jenkins.git'
            }
        }

        stage('Install') {
            steps {
                // Αλλάξαμε το -w /app σε -w /app/my-react-app
                sh "docker run --rm -v \"${WORKSPACE}\":/app -w /app/my-react-app node:20 npm install"
            }
        }

        stage('Test') {
            steps {
                // Αλλάξαμε το -w /app σε -w /app/my-react-app
                sh "docker run --rm -v \"${WORKSPACE}\":/app -w /app/my-react-app node:20 npm test -- --watchAll=false"
            }
        }

        stage('Build') {
            steps {
                // Αλλάξαμε το -w /app σε -w /app/my-react-app
                sh "docker run --rm -v \"${WORKSPACE}\":/app -w /app/my-react-app node:20 npm run build"
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully'
        }

        failure {
            echo 'Build failed'
        }
    }
}